# Gate: `coregister` matches the reference exactly.
#
# `reference/coregister.json` is generated by `reference/gen_coregister.py` against the installed
# `geogrid` package. Every case asserts the overlap origin bitwise, since one ULP there shifts
# the grid window by a whole pixel and misplaces every output.

using ImagePairGeometry
using ImagePairGeometry: nsamples, nlines, xsize, ysize
using JSON3
using Test

const FIX = JSON3.read(read(joinpath(@__DIR__, "reference", "coregister.json"), String))

footprint(d) = ImageFootprint(origin = (Float64(d.origin[1]), Float64(d.origin[2])),
                              spacing = (Float64(d.spacing[1]), Float64(d.spacing[2])),
                              size = (Int(d.size[1]), Int(d.size[2])))

bits(x::Float64) = reinterpret(UInt64, x)

@testset "provenance" begin
    # The fixture records what generated it. PROJ matters because the projected path's transforms
    # come from it; a mismatch would explain a failure that is not our arithmetic.
    p = FIX.provenance
    @test p.proj_version == "9.8.1"
    @info "coregister fixture provenance" autorift = p.autorift_version gdal = p.gdal_version proj = p.proj_version
end

@testset "matches reference: $(c.name)" for c in FIX.cases
    pair = coregister(footprint(c.reference), footprint(c.secondary); dt = 86400.0)
    e = c.expect

    @test pair.reference_offset == (Int(e.x1a), Int(e.y1a))
    @test pair.secondary_offset == (Int(e.x2a), Int(e.y2a))
    @test pair.coordinate.size == (Int(e.xsize1), Int(e.ysize1))

    # The reference returns the overlap as a GDAL geotransform `(W, dx, 0, N, 0, dy)`. Compare
    # origin and spacing bitwise against those slots.
    trans = parse.(Float64, collect(e.trans_hex))
    @test bits(pair.coordinate.origin[1]) == bits(trans[1])
    @test bits(pair.coordinate.origin[2]) == bits(trans[4])
    @test bits(pair.coordinate.spacing[1]) == bits(trans[2])
    @test bits(pair.coordinate.spacing[2]) == bits(trans[6])

    # The reference reports both images' overlap sizes and they must agree — it errors otherwise.
    @test (Int(e.xsize1), Int(e.ysize1)) == (Int(e.xsize2), Int(e.ysize2))
end

@testset "rejects what the reference rejects: $(c.name)" for c in FIX.fail_cases
    @test !isnothing(c.raised)   # the fixture confirms the reference refused this pair
    @test_throws ArgumentError coregister(footprint(c.reference), footprint(c.secondary); dt = 1.0)
end

@testset "dt is carried, not interpreted" begin
    a = ImageFootprint(origin = (0.0, 100.0), spacing = (10.0, -10.0), size = (10, 10))
    for dt in (86400.0, -86400.0, 0.0, 1.5, 365 * 86400.0)
        @test coregister(a, a; dt).dt === Float64(dt)
    end
    @test coregister(a, a; dt = 86400).dt === 86400.0   # Integer accepted, stored as Float64
end

@testset "overlap of an image with itself is the image" begin
    for (origin, spacing, size) in (((300000.0, 7800000.0), (30.0, -30.0), (200, 150)),
                                    ((-1500000.0, 1500000.0), (120.0, -120.0), (64, 64)),
                                    ((0.0, 0.0), (1.0, 1.0), (3, 3)))
        f = ImageFootprint(; origin, spacing, size)
        p = coregister(f, f; dt = 1.0)
        @test p.coordinate.origin == origin
        @test p.coordinate.spacing == spacing
        @test p.coordinate.size == size
        @test p.reference_offset == (0, 0)
        @test p.secondary_offset == (0, 0)
    end
end

@testset "argument errors" begin
    a = ImageFootprint(origin = (0.0, 100.0), spacing = (10.0, -10.0), size = (10, 10))

    # Mismatched spacing: the reference compares EPSG codes; footprints carry no CRS, so the
    # available check is pixel geometry.
    b = ImageFootprint(origin = (0.0, 100.0), spacing = (20.0, -20.0), size = (10, 10))
    @test_throws "matching pixel spacing" coregister(a, b; dt = 1.0)

    # Disjoint footprints.
    far = ImageFootprint(origin = (1e6, 1e6), spacing = (10.0, -10.0), size = (10, 10))
    @test_throws ArgumentError coregister(a, far; dt = 1.0)

    # Grids offset by a fraction of a pixel.
    half = ImageFootprint(origin = (5.0, 95.0), spacing = (10.0, -10.0), size = (10, 10))
    @test_throws "offset by a fraction of a pixel" coregister(a, half; dt = 1.0)
end

@testset "ProjectedCoordinate validation" begin
    @test_throws "size must be positive" ProjectedCoordinate((0.0, 0.0), (1.0, -1.0), (0, 5))
    @test_throws "spacing must be nonzero" ProjectedCoordinate((0.0, 0.0), (0.0, -1.0), (5, 5))
    @test_throws "origin must be finite" ProjectedCoordinate((NaN, 0.0), (1.0, -1.0), (5, 5))
    @test_throws "spacing must be finite" ProjectedCoordinate((0.0, 0.0), (Inf, -1.0), (5, 5))

    c = ProjectedCoordinate(origin = (300000.0, 7800000.0), spacing = (30.0, -30.0), size = (10, 20))
    @test xsize(c) === 30.0
    @test ysize(c) === 30.0     # absolute, so north-up sign does not leak into pixel size
    @test nsamples(c) == 10
    @test nlines(c) == 20

    # Integer inputs promote to a common float type rather than erroring.
    @test ProjectedCoordinate((0, 0), (1, -1), (5, 5)) isa ProjectedCoordinate{Int}
end

@testset "both coordinate systems subtype the interface" begin
    @test ProjectedCoordinate <: ImagePairGeometry.AbstractImageCoordinate
    @test RadarCoordinate <: ImagePairGeometry.AbstractImageCoordinate
    # Every field is required; there is no meaningful default for a radar acquisition.
    @test_throws UndefKeywordError RadarCoordinate()
end

@testset "type stable" begin
    a = ImageFootprint(origin = (0.0, 100.0), spacing = (10.0, -10.0), size = (10, 10))
    # `CoregisteredPair` is parameterized on the coordinate type rather than an element type, so a
    # coregistered projected pair is a `CoregisteredPair{ProjectedCoordinate{Float64}}`.
    @test @inferred(coregister(a, a; dt = 1.0)) isa
        CoregisteredPair{ProjectedCoordinate{Float64}}
end
