# Gate: the integer conversions match compiled C, not our belief about it.
#
# `reference/rounding.csv` is generated by `reference/rounding.c` compiled with `cc -O2` and
# committed, so this runs with no C toolchain. Inputs are given in hex so the comparison is
# against the exact bit pattern C saw, not a decimal that may reparse differently.

using ImagePairGeometry: cround, cround32, ctrunc32, nround
using Test

hex2f(s) = reinterpret(Float64, parse(UInt64, s))

const CASES = let path = joinpath(@__DIR__, "reference", "rounding.csv")
    lines = readlines(path)
    @assert lines[1] == "x_hex,x_dec,std_round_hex,cround32,ctrunc32"
    map(lines[2:end]) do line
        f = split(line, ',')
        (x = hex2f(f[1]), round = hex2f(f[3]),
         cround32 = parse(Int32, f[4]), ctrunc32 = parse(Int32, f[5]))
    end
end

@testset "matches compiled C" begin
    @test !isempty(CASES)
    for c in CASES
        # Bit patterns, not `==`: distinguishes -0.0 from 0.0, which `==` does not.
        @test reinterpret(UInt64, cround(c.x)) == reinterpret(UInt64, c.round)
        @test cround32(c.x) === c.cround32
        @test ctrunc32(c.x) === c.ctrunc32
    end
end

@testset "ties away from zero, not to even" begin
    # The distinction that makes `cround` necessary: Julia's `round` is ties-to-even and would
    # disagree with the reference on every one of these.
    @test cround(0.5) === 1.0
    @test cround(-0.5) === -1.0
    @test cround(2.5) === 3.0
    @test round(0.5) === 0.0
    @test round(2.5) === 2.0

    # `nround` follows `np.round`, which the reference uses in `coregister` — ties to even, so it
    # deliberately disagrees with `cround`.
    @test nround(0.5) === 0.0
    @test nround(2.5) === 2.0
    @test nround(1.5) === 2.0
end

@testset "truncation is not rounding" begin
    # Chip size truncates; offset and search range round. A value just under an integer is where
    # the two part company, and chip-size arithmetic lands there routinely.
    @test ctrunc32(15.999999999999998) === Int32(15)
    @test cround32(15.999999999999998) === Int32(16)
    @test ctrunc32(22.666666666666668) === Int32(22)
    @test cround32(22.666666666666668) === Int32(23)
    @test ctrunc32(-22.99) === Int32(-22)   # toward zero, not floor
    @test cround32(-22.99) === Int32(-23)
end

@testset "out of range throws" begin
    # The reference relies on undefined behavior here; we fail fast instead. See REFERENCE.md.
    @test_throws InexactError cround32(3e9)
    @test_throws InexactError ctrunc32(3e9)
    @test_throws InexactError cround32(NaN)
    @test_throws InexactError ctrunc32(Inf)
end

@testset "type stable and non-allocating" begin
    @test @inferred(cround(0.5)) === 1.0
    @test @inferred(cround32(0.5)) === Int32(1)
    @test @inferred(ctrunc32(0.5)) === Int32(0)
    @test @allocated(cround32(22.7)) == 0
    @test @allocated(ctrunc32(22.7)) == 0
end
